# Generated by Django 4.0.4 on 2022-06-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_classes_regions_category_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=256, verbose_name='lastname')),
                ('fathername', models.CharField(max_length=256, verbose_name='fathername')),
                ('permission', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=250, verbose_name='email')),
                ('email_check', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, default='', max_length=250, verbose_name='contact')),
                ('status', models.CharField(choices=[('0', 'User'), ('1', 'Admin'), ('2', 'SuperAdmin')], default='0', max_length=10, verbose_name='User')),
                ('live', models.CharField(choices=[('0', 'Faol emas'), ('1', 'Faol')], default='0', max_length=10, verbose_name='faol')),
                ('user', models.OneToOneField(help_text='User linked to this admin_page', on_delete=django.db.models.deletion.PROTECT, related_name='admin_page', to=settings.AUTH_USER_MODEL, verbose_name='Related user')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
