# Generated by Django 4.0.4 on 2022-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_cot_discount_products_cost_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.FileField(blank=True, upload_to='app/static/photo/', verbose_name='Foto'),
        ),
    ]
