# Generated by Django 4.0.4 on 2022-06-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_products_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.FileField(blank=True, upload_to='app/static/photos/', verbose_name='Foto'),
        ),
    ]
