# Generated by Django 4.0.4 on 2022-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_collection_active_time_collection_cost_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('0', '1-Toifa'), ('1', '2-Toifa'), ('2', '3-Toifa')], default='0', max_length=10, verbose_name='status_category'),
        ),
    ]
