# Generated by Django 4.0.4 on 2022-06-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale_status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
