# Generated by Django 4.0.4 on 2022-06-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_products_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
