# Generated by Django 4.0.4 on 2022-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_collection_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='product_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
