# Generated by Django 4.0.4 on 2022-06-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_collection_persentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.CharField(choices=[('0', 'Dona'), ('1', 'Pachka')], default='0', max_length=10, verbose_name='amount'),
        ),
    ]
