# Generated by Django 4.0.4 on 2022-06-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_products_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='amount_one_pack',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cost_discount_one_pack',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cost_one_pack',
        ),
    ]
